version: "2"

services:
  jekyll:
    image: jekyll/builder:pages
    volumes: 
      - ./src:/srv/jekyll
    entrypoint: 'jekyll build --watch'
    ports:
      - '4000:4000'
  nginx:
    build: .
    volumes:
      - ./src/_site/:/usr/share/nginx/html/
    ports:
      - '8000:8080'

